Repository cse110-sp25-group18/warmup-exercise, pull requests merged in 2025-04, with the labels that each got.

#5 Uploaded Photo of the second UI design
  design/card-game-design.png
  design/initial-design.png
Labels: documentation

#56 style: change color with color palette
  index.html
  style/spongebob.css
  style/traditional.css
Labels: enhancement

#71 fix: card on front in deck when starting new game
  script/views/SystemView.js
Labels: bug
